services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prestashop
    ports:
      - "3306:3306"

  prestashop:
    image: prestashop/prestashop:8
    restart: always
    ports:
      - "8080:80"
    environment:
      DB_SERVER: db
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: root
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: localhost:8080
    depends_on:
      - db
    volumes:
      - ./modules/ps_shipping:/var/www/html/modules/ps_shipping

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db